### ISSUE TITLE
Zaak detail: configure Taken

### ISSUE THREAD

**Issue by kelvincy** [GemeenteUtrecht/zaakafhandelcomponent#152]
## 1. Adviesvraag/Accorderingsvraag configureren
**`"context": "advice-approve"`**
- Zaakinformatie
- Selecteer relevante documenten
- Toelichting
- Adviseurs/Accordeurs (serieel/parallel)
- Uiterste datum

`GET response`

```json
{
  "context": {
    "advice-approve": {
      "review-type": "approve | advice",
      "titel":"string",
      "zaakinformatie":{
        "omschrijving":"string",
        "toelichting":"string"
      },
     "documenten":[
        {
           "identificatie":"string",
           "bestandsnaam":"string",
           "downloadUrl":"string",
           "beschrijving":"string"
        }
      ]
    }
  }
}
```

`POST request body`
```json
{
   "selectedDocuments":[
      "identificatie1",
      "identificatie2"
   ],
   "assignedUsers":[
      {
       "deadline":"21-02-2021",
       "users":[
          "username1",
          "username2"
       ]
      },
      {
       "deadline":"21-02-2021",
       "users":[
          "username3",
          "username4"
       ]
      }
   ],
   "toelichting":"string"
}
```

## 2. Document selecteren
**`"context": "document-select"`**

`GET response`
```json
{
  "context": {
    "document-select": {
      "documenten":[
        {
           "identificatie":"string",
           "bestandsnaam":"string",
           "downloadUrl":"string",
           "beschrijving":"string",
           "versie": "string",
           "bestandsomvang": "number"
        }
      ]
    }
  }
}
```

`POST request body`
```json
{
   "selectedDocuments":[
      "identificatie1",
      "identificatie2"
   ]
}
```

## 3. Dynamisch gegenereerde form
**`"context": "dynamic-form"`**

`GET response`
```json
{
  "context": {
    "dynamic-form": {
      "titel":"string",
      "zaakinformatie":{
        "omschrijving":"string",
        "toelichting":"string"
      },
      "formFields": {
        "name": {
          "title": "string",
          "inputType": "'enum' | 'string' | 'long' | 'boolean' | 'date'",
          "value": "string",
          "enum": ["string","string"]
        }
      }
    }
  }
}
```
`POST request body`
```json
{
  "formData": [
    {
      "name": "string",
      "value": "string | long | boolean | date"
    }
  ]
}
```

## 4. Digitale ondertekening
**`"context": "sign-document"`**

`GET response`
```json
{
  "context": {
     "sign-document": {
        "documenten":[
          {
             "identificatie":"string",
             "bestandsnaam":"string",
             "downloadUrl":"string",
             "beschrijving":"string",
             "versie": "string",
             "bestandsomvang": "number"
          }
        ]
     }
  }
}
```

`POST request body`
```json
{
   "selectedDocuments":[
      "identificatie1",
      "identificatie2"
   ],
   "assignedUsers": [
     {
       "username": "string",
       "email"?: "string",
       "firstName"?: "string",
       "lastName"?: "string"
     }
   ]
}
```

**Comment by damm89** [comment]
## 1. Adviesvraag/Accorderingsvraag configureren
**`"type": "advice-approve"`**
- Zaakinformatie
- Selecteer relevante documenten
- Toelichting
- Adviseurs/Accordeurs (serieel/parallel)
- Uiterste datum

`GET response`

```json
{
  "type":"advice-approve",
   "titel":"string",
   "zaakinformatie":{
      "omschrijving":"string",
      "toelichting":"string"
   },
   "documenten":[
      {
         "identificatie":"string",
         "bestandsnaam":"string",
         "~~downloadUrl~~**readUrl**":"string",
         "beschrijving":"string"
      }
   ]
}
```

`POST request body`
```json
{
   "selectedDocuments":[
      "identificatie1",
      "identificatie2"
   ],
   "assignedUsers":[
      {
         "deadline":"21-02-2021",
         "users":[
            "username1",
            "username2"
         ]
      }**,
      {
         "deadline":"22-02-2021",
         "users":[
            "username3",
            "username4"
         ]
      }**
   ],
   "toelichting":"string"
}
```

**Comment by damm89** [comment]
Started here:
https://github.com/GemeenteUtrecht/zaakafhandelcomponent/pull/161/files

**Comment by kelvincy** [comment]
See https://github.com/GemeenteUtrecht/zac-lite/ for generic response

**Comment by kelvincy** [comment]
@sergei-maertens @damm89 

When I POST to `/api/camunda/task-data/da445f6b-3bb7-11eb-883c-56e3c4cb288a`

I receive this 500 error: 

`TypeError at /api/camunda/task-data/da445f6b-3bb7-11eb-883c-56e3c4cb288a
__init__() missing 1 required positional argument: 'review_type'
`

**Comment by damm89** [comment]
Proposal for user task post payload implementation

**### Wish list:**
- Single endpoint to post to

**### Implications wish list:**
- Requires task id to be sent with all post payloads
- Payload will be polymorphic (i.e., changes on form_key of task)

**### Proposal:**
- Extend `(Get)TaskContextView `with a post method
- Extend serializer_mapping in `PolymorphicSerializer` to include the option to specify serializers for different `HTTP` methods
- Extend `register` with option kwarg that allows you to specificy whether to "overwrite" or "update" `REGISTRY` instead of current overwrite default

**### Implementation path:**
- Adjust REGISTRY
- Adjust register function
- Adjust `PolymorphicSerializer.__init__`
- Adjust `PolymorphicSerializer._get_serializer_from_instance` to allow for extended options in `serializer_mapping`
- Add `to_internal_value` method to `PolymorphicSerializer`
- Create dataclass objects and respective serializers to deal with payload requirements as stated above and decorate them with `usertask_context_serializer`.
- Add `post` method to `(Get)TaskContextView` where task is retrieved and serializer is picked according to task.form_key.
- Implement complete_task function in `(Get)TaskContextView.post`.
- Write tests (I know... TDD dictates I should do it the other way around... :()

**Comment by sergei-maertens** [comment]
> Extend (Get)TaskContextView with a post method

:+1: 

> Extend serializer_mapping in PolymorphicSerializer to include the option to specify serializers for different HTTP methods

Maybe define an optional `serializer_mapping_for_write` next to the existing `serializer_mapping`? The default could be that the same serializers are used for read & write, which is usually the case with polymorphism. However, the Camunda stuff is different (because of the included `context` key which we don't want for writes).

> Extend register with option kwarg that allows you to specificy whether to "overwrite" or "update" REGISTRY instead of current overwrite default

I don't see this overwrite or update mechanism requirement? I'd opt for `@register(form_key: str, read_serializer: type, write_serializer: type):` as a signature, and store that in the registry as: `REGISTRY[form_key] = (func, read_serializer, write_serializer)`

IMO we don't need to register another function with the registry, wouldn't it be sufficient to have a code-path specific method on each serializer `def on_task_submission(self):`:

- we have all the data from the frontend in the serializer
- we validate the data from the frontend using the serializer
- we can pass the `task` object from the view in the serializer context, so that the serializer can access `self.context["task"]` and we can store all the task data to the remote API's from there.

> Create dataclass objects and respective serializers to deal with payload requirements as stated above and decorate them with usertask_context_serializer.

The `usertask_context_serializer` decorator is not needed for the write actions, this only serves to nest the context in the `context` key in the main serializer level.

> I know... TDD dictates I should do it the other way around... :(

TDD is only one tool in a large toolbox, it's not a religion ;)

**Comment by damm89** [comment]
> 
> Maybe define an optional `serializer_mapping_for_write` next to the existing `serializer_mapping`? The default could be that the same serializers are used for read & write, which is usually the case with polymorphism. However, the Camunda stuff is different (because of the included `context` key which we don't want for writes).

Sure!

> I don't see this overwrite or update mechanism requirement? I'd opt for `@register(form_key: str, read_serializer: type, write_serializer: type):` as a signature, and store that in the registry as: `REGISTRY[form_key] = (func, read_serializer, write_serializer)`

https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/3ef3f6a89795c75ba614a32bfab4e6f06549ff3c/backend/src/zac/camunda/user_tasks/context.py#L54
```
    """
    Register the form key with the given callback and serializer class.
    """

    def decorator(func: callable):
        if form_key in REGISTRY:
            warnings.warn(
                f"Overwriting existing form key '{form_key}' in registry.",
                DuplicateFormKeyWarning,
            )

        REGISTRY[form_key] = (func, serializer_cls)

        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            return func(*args, **kwargs)

    return decorator
```

> IMO we don't need to register another function with the registry, wouldn't it be sufficient to have a code-path specific method on each serializer `def on_task_submission(self):`:
> 
>     * we have all the data from the frontend in the serializer
> 
>     * we validate the data from the frontend using the serializer
> 
>     * we can pass the `task` object from the view in the serializer context, so that the serializer can access `self.context["task"]` and we can store all the task data to the remote API's from there.

Sure!

> The `usertask_context_serializer` decorator is not needed for the write actions, this only serves to nest the context in the `context` key in the main serializer level.

Okay. :-)
