### ISSUE TITLE
Make object schemas consistent  throughout various API endpoints.

### ISSUE THREAD

**Issue by svenvandescheur** [GemeenteUtrecht/zaakafhandelcomponent#417]
The frontend uses interface to know the shape of these objects, if the schema's are inconsistent, these don't always work.

Case in point: object types, which are sometimes embedded, sometimes URL references:

> I have a question about related objects, the endpoint for zaak related objects returns object with a nested object type, the search returns an url to the object type. Can we make this consistent?

**Comment by sergei-maertens** [comment]
@annashamray @damm89 any idea what the impact on performance will be for this?

**Comment by svenvandescheur** [comment]
Please not: I currently have no preference of the correct way for this. I'd only like it to be consistent (which applies to all objects btw).

**Comment by annashamray** [comment]
@svenvandescheur Can you clear out which endpoints have inconsistent objecttypes. It looks like it's because of the confusion of zaakobject.object_type and object.object_type

`/api/core/cases/{bronorganisatie}/{identificatie}/objects` returns `zaakobject.object_type` in the response (which is string now but should be enum) 
`/api/core/objects` return `object.object_type` which is the url. 

We can add help texts and enum to the endpoint `/api/core/cases/{bronorganisatie}/{identificatie}/objects`
And I actually don't know what else could be done to eliminate the confusion

**Comment by damm89** [comment]
> Please note: I currently have no preference of the correct way for this. I'd only like it to be consistent (which applies to all objects btw).

Applies to all objects? As in objects from objects API or data objects or zaakobjects??

**Comment by damm89** [comment]
> Case in point: object types, which are sometimes embedded, sometimes URL references:

Yeah, I can see how that is confusing. It happens in several cases and sometimes it gets quite incestuous. 

Not a very helpful remark perhaps, but aligning response shapes for endpoints just for the sake of aligning them seems kind of stupid. Usually there was a reason why something was built a particular way. Those reasons might be obfuscated but may still exist (or not). I would say it is quite hard to align everything post hoc but we should probably consider it on a per case basis where an issue is created with the annoyance described. I can pick those up in between tasks and at least try to figure out where the inconsistency came/is coming from and then see if it can be aligned or not and then see what the performance impact is (although, again, I'm not really pro aligning just for the sake of aligning, the API docs are quite descriptive and detailed).

One of the reasons why it happens is because we're reusing serializers which aren't created for that specific job but are more generic. Sometimes those serializers over-deliver, so they spit out more data than needed. Sometimes those extra fields can be url references or "resolved objects", depending on the more generic purpose of that serializer. 

As for the performance impact: there are times now where we are fetching resources and "resolving relations" (usually means a zaak url is resolved for the zaak object for example), and then we aren't doing _anything_ with that data. Those should be ripped out - I'll make a PR for them. It's not going to change the world though, it's just old code that needs some cleaning up.

**Comment by sergei-maertens** [comment]
+1 on what Daniel says.

We do try to re-use serializers as much as possible to have consistent endpoints, and if it diverges in places, it is likely that there's a reason for that. However, that broad idea shouldn't be used to just shut down every remark that will come about this in the future.

So, I'm in favour of the following procedure:

1. Point out specific problems to backend development
2. Backend development either clears up a misconception or
3. Backend figures out _why_ this was done so, deliberately
4. The findings are communicated back
5. Ideally, API documentation is improved (description, help text... to have an answer for the next time the question comes up)
6. Where relevant, we may also have to update the project documentation to cover this case and be able to refer to it later (the Sphinx docs).

**Comment by svenvandescheur** [comment]
I get that the backend alters shapes because of various reasons, however I don't feel like the impact for the frontend is taken into consideration when doing this. Altering the shape of an object to suit the nee of a particular endpoint might seem like a good idea but causes confusions and problems later on the road. There's probably a good reason for it, but also a good reason not to so.

I'll leave this issue for now due to it's contents are highly opinionated, but please do take the frontend into consideration when designing shapes of objects and/or serializers.
